name: EDLM Portal Backend Code CI/CD

on:
  push: 
    branches:
        - dev
  pull_request:
    branches: 
      - main
    types: [opened, synchronize]

jobs:
  code-test:
    # Kicks off the workflow and prepares Github to run coverage test using a ubuntu-latest container.
    name: Code CI/CD
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.12'
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    # Install dependencies required for tests
    - name: Install Dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install libxml2-dev libxmlsec1-dev -y --no-install-recommends
        python -m pip install --upgrade pip
        pip install setuptools
        pip install pylint
        pip install -r ./requirements.txt
    
    - name: Lint
      run: pylint /app
    # Start running test scripts and generate the coverage report
    # - name: Generate Coverage Report
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: ${{ secrets.AWS_REGION }}
    #     DB_NAME: ${{ secrets.DB_NAME }}
    #     DB_HOST: ${{ secrets.DB_HOST }}
    #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #     DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
    #     DB_USER: ${{ secrets.DB_USER }}
    #     DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
    #     DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
    #     DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
    #     LOG_PATH: ${{ secrets.LOG_PATH}}
    #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #   run: |
    #     echo "Create openlxp docker network"
    #     docker network create openlxp
    #     echo "Docker network successfully created"
    #     echo "Running coverage unit test"
    #     docker compose run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
    #                        -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
    #                        -e AWS_REGION=${{ secrets.AWS_REGION }} \
    #                        -e DB_NAME=${{ secrets.DB_NAME }} \
    #                        -e DB_HOST=${{ secrets.DB_HOST }} \
    #                        -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
    #                        -e DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} \
    #                        -e DB_USER=${{ secrets.DB_USER }} \
    #                        -e DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }} \
    #                        -e DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }} \
    #                        -e DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }} \
    #                        app sh -c \
    #                        "python coverage run manage.py test --tag=unit && flake8 && coverage report && coverage report --fail-under=80"